import { PatternIdEnum } from '#shared/types/market';

export enum PatternFamilyEnum {
  Candle = 'candle',
  Structure = 'structure',
  PriceAction = 'priceAction',
  Volume = 'volume',
  Volatility = 'volatility',
  Trend = 'trend',
  Momentum = 'momentum',
  Liquidity = 'liquidity',
}

export enum PatternSignalRoleEnum {
  Actionable = 'actionable',
  Context = 'context',
  Warning = 'warning',
}

const FAMILY_MAP = new Map<PatternIdEnum, PatternFamilyEnum>([
  // candle
  [PatternIdEnum.Hammer, PatternFamilyEnum.Candle],
  [PatternIdEnum.InvertedHammer, PatternFamilyEnum.Candle],
  [PatternIdEnum.HangingMan, PatternFamilyEnum.Candle],
  [PatternIdEnum.ShootingStar, PatternFamilyEnum.Candle],
  [PatternIdEnum.Doji, PatternFamilyEnum.Candle],
  [PatternIdEnum.LongLeggedDoji, PatternFamilyEnum.Candle],
  [PatternIdEnum.DragonflyDoji, PatternFamilyEnum.Candle],
  [PatternIdEnum.GravestoneDoji, PatternFamilyEnum.Candle],
  [PatternIdEnum.SpinningTop, PatternFamilyEnum.Candle],
  [PatternIdEnum.BullishMarubozu, PatternFamilyEnum.Candle],
  [PatternIdEnum.BearishMarubozu, PatternFamilyEnum.Candle],
  [PatternIdEnum.BullishKicker, PatternFamilyEnum.Candle],
  [PatternIdEnum.BearishKicker, PatternFamilyEnum.Candle],
  [PatternIdEnum.ThreeWhiteSoldiers, PatternFamilyEnum.Candle],
  [PatternIdEnum.ThreeBlackCrows, PatternFamilyEnum.Candle],
  [PatternIdEnum.RisingThreeMethods, PatternFamilyEnum.Candle],
  [PatternIdEnum.FallingThreeMethods, PatternFamilyEnum.Candle],
  [PatternIdEnum.MatHold, PatternFamilyEnum.Candle],
  [PatternIdEnum.BullishSeparatingLines, PatternFamilyEnum.Candle],
  [PatternIdEnum.BearishSeparatingLines, PatternFamilyEnum.Candle],
  [PatternIdEnum.UpsideTasukiGap, PatternFamilyEnum.Candle],
  [PatternIdEnum.DownsideTasukiGap, PatternFamilyEnum.Candle],
  [PatternIdEnum.OnNeck, PatternFamilyEnum.Candle],
  [PatternIdEnum.InNeck, PatternFamilyEnum.Candle],
  [PatternIdEnum.Thrusting, PatternFamilyEnum.Candle],
  [PatternIdEnum.BullishBreakawayGap, PatternFamilyEnum.Candle],
  [PatternIdEnum.BearishBreakawayGap, PatternFamilyEnum.Candle],
  [PatternIdEnum.RunawayGapUp, PatternFamilyEnum.Candle],
  [PatternIdEnum.RunawayGapDown, PatternFamilyEnum.Candle],
  [PatternIdEnum.ExhaustionGapUp, PatternFamilyEnum.Candle],
  [PatternIdEnum.ExhaustionGapDown, PatternFamilyEnum.Candle],
  [PatternIdEnum.GapFillBullish, PatternFamilyEnum.Candle],
  [PatternIdEnum.GapFillBearish, PatternFamilyEnum.Candle],
  [PatternIdEnum.IslandReversalBottom, PatternFamilyEnum.Candle],
  [PatternIdEnum.IslandReversalTop, PatternFamilyEnum.Candle],
  [PatternIdEnum.BullishEngulfing, PatternFamilyEnum.Candle],
  [PatternIdEnum.BearishEngulfing, PatternFamilyEnum.Candle],
  [PatternIdEnum.BullishHarami, PatternFamilyEnum.Candle],
  [PatternIdEnum.BearishHarami, PatternFamilyEnum.Candle],
  [PatternIdEnum.PiercingLine, PatternFamilyEnum.Candle],
  [PatternIdEnum.DarkCloudCover, PatternFamilyEnum.Candle],
  [PatternIdEnum.MorningStar, PatternFamilyEnum.Candle],
  [PatternIdEnum.EveningStar, PatternFamilyEnum.Candle],
  [PatternIdEnum.TweezerBottom, PatternFamilyEnum.Candle],
  [PatternIdEnum.TweezerTop, PatternFamilyEnum.Candle],
  [PatternIdEnum.InsideBar, PatternFamilyEnum.Candle],
  [PatternIdEnum.BullishFvg, PatternFamilyEnum.Candle],
  [PatternIdEnum.BearishFvg, PatternFamilyEnum.Candle],
  // structure
  [PatternIdEnum.BullishBos, PatternFamilyEnum.Structure],
  [PatternIdEnum.BearishBos, PatternFamilyEnum.Structure],
  [PatternIdEnum.BullishChoch, PatternFamilyEnum.Structure],
  [PatternIdEnum.BearishChoch, PatternFamilyEnum.Structure],
  [PatternIdEnum.HigherHigh, PatternFamilyEnum.Structure],
  [PatternIdEnum.HigherLow, PatternFamilyEnum.Structure],
  [PatternIdEnum.LowerHigh, PatternFamilyEnum.Structure],
  [PatternIdEnum.LowerLow, PatternFamilyEnum.Structure],
  // price action
  [PatternIdEnum.DoubleTop, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.DoubleBottom, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.TripleTop, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.TripleBottom, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.HeadAndShoulders, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.InverseHeadAndShoulders, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.BullishFlag, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.BearishFlag, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.BullishPennant, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.BearishPennant, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.AscendingTriangle, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.DescendingTriangle, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.SymmetricalTriangle, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.RisingWedge, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.FallingWedge, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.RectangleBreakoutUp, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.RectangleBreakoutDown, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.RangeRejectionHigh, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.RangeRejectionLow, PatternFamilyEnum.PriceAction],
  [PatternIdEnum.ChannelBreakout, PatternFamilyEnum.PriceAction],
  // volume
  [PatternIdEnum.VolumeSpikeBullish, PatternFamilyEnum.Volume],
  [PatternIdEnum.VolumeSpikeBearish, PatternFamilyEnum.Volume],
  [PatternIdEnum.ClimaxVolumeTop, PatternFamilyEnum.Volume],
  [PatternIdEnum.ClimaxVolumeBottom, PatternFamilyEnum.Volume],
  [PatternIdEnum.LowVolumePullbackBullish, PatternFamilyEnum.Volume],
  [PatternIdEnum.LowVolumePullbackBearish, PatternFamilyEnum.Volume],
  // volatility
  [PatternIdEnum.AtrExpansionBreakout, PatternFamilyEnum.Volatility],
  [PatternIdEnum.AtrCompression, PatternFamilyEnum.Volatility],
  [PatternIdEnum.VolatilitySqueeze, PatternFamilyEnum.Volatility],
  [PatternIdEnum.WideRangeCandle, PatternFamilyEnum.Volatility],
  // trend
  [PatternIdEnum.GoldenCross, PatternFamilyEnum.Trend],
  [PatternIdEnum.DeathCross, PatternFamilyEnum.Trend],
  [PatternIdEnum.EmaBullishStack, PatternFamilyEnum.Trend],
  [PatternIdEnum.EmaBearishStack, PatternFamilyEnum.Trend],
  [PatternIdEnum.MaPullbackBullish, PatternFamilyEnum.Trend],
  [PatternIdEnum.MaPullbackBearish, PatternFamilyEnum.Trend],
  [PatternIdEnum.TrendlineBreakUp, PatternFamilyEnum.Trend],
  [PatternIdEnum.TrendlineBreakDown, PatternFamilyEnum.Trend],
  [PatternIdEnum.RetestSupport, PatternFamilyEnum.Trend],
  [PatternIdEnum.RetestResistance, PatternFamilyEnum.Trend],
  // momentum
  [PatternIdEnum.RsiBullishDivergence, PatternFamilyEnum.Momentum],
  [PatternIdEnum.RsiBearishDivergence, PatternFamilyEnum.Momentum],
  [PatternIdEnum.MacdBullishCross, PatternFamilyEnum.Momentum],
  [PatternIdEnum.MacdBearishCross, PatternFamilyEnum.Momentum],
  [PatternIdEnum.MacdBullishDivergence, PatternFamilyEnum.Momentum],
  [PatternIdEnum.MacdBearishDivergence, PatternFamilyEnum.Momentum],
  [PatternIdEnum.StochasticOversoldReversal, PatternFamilyEnum.Momentum],
  [PatternIdEnum.StochasticOverboughtReversal, PatternFamilyEnum.Momentum],
  [PatternIdEnum.MomentumBreakout, PatternFamilyEnum.Momentum],
  [PatternIdEnum.MomentumExhaustion, PatternFamilyEnum.Momentum],
  // liquidity
  [PatternIdEnum.LiquiditySweepHigh, PatternFamilyEnum.Liquidity],
  [PatternIdEnum.LiquiditySweepLow, PatternFamilyEnum.Liquidity],
  [PatternIdEnum.StopHuntHigh, PatternFamilyEnum.Liquidity],
  [PatternIdEnum.StopHuntLow, PatternFamilyEnum.Liquidity],
  [PatternIdEnum.EqualHighs, PatternFamilyEnum.Liquidity],
  [PatternIdEnum.EqualLows, PatternFamilyEnum.Liquidity],
  [PatternIdEnum.OrderBlockBullish, PatternFamilyEnum.Liquidity],
  [PatternIdEnum.OrderBlockBearish, PatternFamilyEnum.Liquidity],
  [PatternIdEnum.BreakerBlockBullish, PatternFamilyEnum.Liquidity],
  [PatternIdEnum.BreakerBlockBearish, PatternFamilyEnum.Liquidity],
]);

const ROLE_MAP = new Map<PatternIdEnum, PatternSignalRoleEnum>([
  // candle — actionable
  [PatternIdEnum.Hammer, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.InvertedHammer, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.HangingMan, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.ShootingStar, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BullishMarubozu, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BearishMarubozu, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BullishKicker, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BearishKicker, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.ThreeWhiteSoldiers, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.ThreeBlackCrows, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.RisingThreeMethods, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.FallingThreeMethods, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.MatHold, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BullishSeparatingLines, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BearishSeparatingLines, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.UpsideTasukiGap, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.DownsideTasukiGap, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.OnNeck, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.InNeck, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.Thrusting, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BullishBreakawayGap, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BearishBreakawayGap, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.RunawayGapUp, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.RunawayGapDown, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.GapFillBullish, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.GapFillBearish, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.IslandReversalBottom, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.IslandReversalTop, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BullishEngulfing, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BearishEngulfing, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.PiercingLine, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.DarkCloudCover, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.MorningStar, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.EveningStar, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.TweezerBottom, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.TweezerTop, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BullishFvg, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BearishFvg, PatternSignalRoleEnum.Actionable],
  // candle — context
  [PatternIdEnum.Doji, PatternSignalRoleEnum.Context],
  [PatternIdEnum.LongLeggedDoji, PatternSignalRoleEnum.Context],
  [PatternIdEnum.DragonflyDoji, PatternSignalRoleEnum.Context],
  [PatternIdEnum.GravestoneDoji, PatternSignalRoleEnum.Context],
  [PatternIdEnum.SpinningTop, PatternSignalRoleEnum.Context],
  [PatternIdEnum.BullishHarami, PatternSignalRoleEnum.Context],
  [PatternIdEnum.BearishHarami, PatternSignalRoleEnum.Context],
  [PatternIdEnum.InsideBar, PatternSignalRoleEnum.Context],
  // candle — warning
  [PatternIdEnum.ExhaustionGapUp, PatternSignalRoleEnum.Warning],
  [PatternIdEnum.ExhaustionGapDown, PatternSignalRoleEnum.Warning],
  // structure — actionable
  [PatternIdEnum.BullishBos, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BearishBos, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BullishChoch, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BearishChoch, PatternSignalRoleEnum.Actionable],
  // structure — context
  [PatternIdEnum.HigherHigh, PatternSignalRoleEnum.Context],
  [PatternIdEnum.HigherLow, PatternSignalRoleEnum.Context],
  [PatternIdEnum.LowerHigh, PatternSignalRoleEnum.Context],
  [PatternIdEnum.LowerLow, PatternSignalRoleEnum.Context],
  // price action — actionable
  [PatternIdEnum.DoubleTop, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.DoubleBottom, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.TripleTop, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.TripleBottom, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.HeadAndShoulders, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.InverseHeadAndShoulders, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BullishFlag, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BearishFlag, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BullishPennant, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BearishPennant, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.AscendingTriangle, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.DescendingTriangle, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.SymmetricalTriangle, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.RisingWedge, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.FallingWedge, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.RectangleBreakoutUp, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.RectangleBreakoutDown, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.RangeRejectionHigh, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.RangeRejectionLow, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.ChannelBreakout, PatternSignalRoleEnum.Actionable],
  // volume
  [PatternIdEnum.VolumeSpikeBullish, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.VolumeSpikeBearish, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.ClimaxVolumeTop, PatternSignalRoleEnum.Warning],
  [PatternIdEnum.ClimaxVolumeBottom, PatternSignalRoleEnum.Warning],
  [PatternIdEnum.LowVolumePullbackBullish, PatternSignalRoleEnum.Context],
  [PatternIdEnum.LowVolumePullbackBearish, PatternSignalRoleEnum.Context],
  // volatility
  [PatternIdEnum.AtrExpansionBreakout, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.AtrCompression, PatternSignalRoleEnum.Context],
  [PatternIdEnum.VolatilitySqueeze, PatternSignalRoleEnum.Warning],
  [PatternIdEnum.WideRangeCandle, PatternSignalRoleEnum.Warning],
  // trend
  [PatternIdEnum.GoldenCross, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.DeathCross, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.EmaBullishStack, PatternSignalRoleEnum.Context],
  [PatternIdEnum.EmaBearishStack, PatternSignalRoleEnum.Context],
  [PatternIdEnum.MaPullbackBullish, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.MaPullbackBearish, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.TrendlineBreakUp, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.TrendlineBreakDown, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.RetestSupport, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.RetestResistance, PatternSignalRoleEnum.Actionable],
  // momentum
  [PatternIdEnum.RsiBullishDivergence, PatternSignalRoleEnum.Warning],
  [PatternIdEnum.RsiBearishDivergence, PatternSignalRoleEnum.Warning],
  [PatternIdEnum.MacdBullishCross, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.MacdBearishCross, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.MacdBullishDivergence, PatternSignalRoleEnum.Warning],
  [PatternIdEnum.MacdBearishDivergence, PatternSignalRoleEnum.Warning],
  [PatternIdEnum.StochasticOversoldReversal, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.StochasticOverboughtReversal, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.MomentumBreakout, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.MomentumExhaustion, PatternSignalRoleEnum.Warning],
  // liquidity
  [PatternIdEnum.LiquiditySweepHigh, PatternSignalRoleEnum.Warning],
  [PatternIdEnum.LiquiditySweepLow, PatternSignalRoleEnum.Warning],
  [PatternIdEnum.StopHuntHigh, PatternSignalRoleEnum.Warning],
  [PatternIdEnum.StopHuntLow, PatternSignalRoleEnum.Warning],
  [PatternIdEnum.EqualHighs, PatternSignalRoleEnum.Context],
  [PatternIdEnum.EqualLows, PatternSignalRoleEnum.Context],
  [PatternIdEnum.OrderBlockBullish, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.OrderBlockBearish, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BreakerBlockBullish, PatternSignalRoleEnum.Actionable],
  [PatternIdEnum.BreakerBlockBearish, PatternSignalRoleEnum.Actionable],
]);

export function getPatternFamily(id: PatternIdEnum): PatternFamilyEnum {
  return FAMILY_MAP.get(id) ?? PatternFamilyEnum.Candle;
}

export function getPatternSignalRole(id: PatternIdEnum): PatternSignalRoleEnum {
  return ROLE_MAP.get(id) ?? PatternSignalRoleEnum.Actionable;
}
