export const EXTRA_CONFIDENCE = {
  invertedHammer: 64,
  hangingMan: 64,
  longLeggedDoji: 48,
  dragonflyDoji: 58,
  gravestoneDoji: 58,
  spinningTop: 46,
  bullishMarubozu: 68,
  bearishMarubozu: 68,
  bullishKicker: 78,
  bearishKicker: 78,
  threeWhiteSoldiers: 76,
  threeBlackCrows: 76,
  bullishHarami: 62,
  bearishHarami: 62,
  piercingLine: 66,
  darkCloudCover: 66,
  morningStar: 72,
  eveningStar: 72,
  tweezerBottom: 60,
  tweezerTop: 60,
} as const;

export const EXTRA_THRESHOLDS = {
  haramiMaxBodyFactor: 0.75,
  starMaxBodyPct: 0.35,
  starBodyGapFactor: 0.1,
  midpointFactor: 0.5,
  tweezerTolerancePct: 0.001,
  marubozuMinBodyPct: 0.9,
  marubozuMaxShadowPct: 0.05,
  spinningTopMinBodyPct: 0.1,
  spinningTopMaxBodyPct: 0.35,
  longLeggedDojiMinShadowPct: 0.35,
  dragonflyUpperShadowMaxPct: 0.1,
  gravestoneLowerShadowMaxPct: 0.1,
} as const;
